public enum Metier
{
    SECRETAIRE,
    PATRON,
    CUISINIER,
    TECHNICIEN_SON_VIDEO,
    GRAPHISTE,
    RESPONSABLE_RESEAUX_SOCIAUX,
    CONCIERGE,
    PAYSAGISTE,
    COMPTABLE,
    RESPONSABLE_RESEAU,
    TECHNICIEN_RESEAU
}
